apiVersion: v1
kind: PersistentVolume
metadata:
  name: addrevamp-cms-azure-file-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: addrevamp-cms
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: addrevamp-cms-handle
    volumeAttributes:
      server: stinsuranceazassedev001.file.core.windows.net
      shareName: cms
    nodeStageSecretRef:
      name: azure-secret-cms
      namespace: insurance
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock
    - nobrl
