apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: addrevamp-www-azure-file-pvc
  namespace: insurance
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: addrevamp-www
  volumeMode: Filesystem
  volumeName: addrevamp-www-azure-file-pv
